branches:
  except:
    - PathOfBuilding
 
jobs:
  include:
  - stage: build OSX
    os: osx
    language: objective-c
    env:
      - PATH=/usr/local/opt/qt/bin:$PATH
      - LDFLAGS=-L/usr/local/opt/qt/lib
      - CPPFLAGS=-I/usr/local/opt/qt/include
      - PKG_CONFIG_PATH=/usr/local/opt/qt/lib/pkgconfig
    addons:
      homebrew:
        packages:
          - make
          - ninja
    script:
      - make -f Makefile.darwin clean
      - make -f Makefile.darwin tools
      - make -f Makefile.darwin
      - tar -cf - PathOfBuilding.app | xz -c > PathOfBuilding.darwin.tar.xz

  - stage: build Linux        
    os: linux
    dist: bionic
    language: cpp
    addons:
      apt:
        packages:
          - build-essential
          - ninja-build
    script:
      - make -f Makefile.linux clean
      - make -f Makefile.linux tools
      - make -f Makefile.linux
      - tar -cf - PathOfBuilding | xz -c > PathOfBuilding.linux.tar.xz
      - tar -cf - -C ${TRAVIS_BUILD_DIR}/PathOfBuilding/ $(ls -A ${TRAVIS_BUILD_DIR}"/PathOfBuilding/") | xz -c > PathOfBuilding.linux.tar.xz

before_deploy:
  - export TR_TAG="nightly-$(date +'%Y/%m/%d')"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      git config --local user.name "aspel"
      git config --local user.email "aspellip@gmail.com"
      git tag -f PathOfBuilding
      git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
      git push -f gh PathOfBuilding
      git remote remove gh
      export ARCHIVE_NAME="PathOfBuilding.darwin.tar.xz"
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export ARCHIVE_NAME="PathOfBuilding.linux.tar.xz"
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "${TRAVIS_BUILD_DIR}/${ARCHIVE_NAME}"
  name: "PathOfBuilding"
  overwrite: true
  target_commitish: $TRAVIS_COMMIT

after_deploy:
  - "curl -X PATCH -H 'Accept: application/vnd.github.v3+json' -H \"Authorization: token ${GITHUB_TOKEN}\" https://api.github.com/repos/aspel/pobfrontend/releases/22137604 -d \"{ 'tag_name':'PathOfBuilding','target_commitish': 'master','name': 'PathOfBuilding','body': \\\"build by Travis CI ${TR_TAG}\\\", 'draft': false, 'prerelease': false }\""
